# This is a basic workflow to help you get started with Actions

name: Github-test

# Controls when the workflow will run
on:
  push: 
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  my_testing:
   runs-on: ubuntu-latest
   
   steps:
     - name: Print Hello
     run : echo "Hello from testing"

  my_deploy:
    runs-on: ubuntu-latest
    
    steps: 
    - name : Print Hello
    run : echo "Hello from deploy"
    
