

name: Github-test

on:
  push: 
    branches: 
      - main

jobs:  
  my_testing:
   runs-on: ubuntu-latest
   
   steps:
     - name: Print Hello
     run : echo "Hello from testing"

  my_deploy:
    runs-on: ubuntu-latest
    
    steps: 
    - name : Print Hello
    run : echo "Hello from deploy"
    
