name: My-GithubActions
env:
  APPLICATION_NAME        : "MyFlask"
  DEPLOY_PACKAGE_NAME     : "flask_deploy_version ${{  github.sha  }}"

on:
  push:
    branches:
      - main
      
jobs:
  my_testing:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello message testing
      run : echo "Hello from testing"
    
    - name: Execute few commands
      run : |
        echo "Hello mes1"
        echo "Hello mes 2"
        echo "Application name is ${{ env.APPLICATION_NAME }}"
        
    - name : List current folder (1)
      run : ls -la
      
    - name : Git Clone my repo
      uses: actions/checkout@v1
      
    - name : List current folder (2)
      run : ls -la
      
      
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    env: 
      VAR1 : "This is Job Level 1"
      VAR2 : "This is JobLevel 2"
      
    steps:
    - name: Print Hello message deploy
      run : echo "Hello from deploy"
      
    - name : Print env vars
      run: |
        echo "Var1 = ${{ env.VAR1 }}"
        echo "Var2 = ${{ env.VAR2 }}"
        echo "VAR3 = $LOCAL_VAR "
      env :
        LOCAL_VAR : "This is LOCAL"
      
    - name: Printing deployment package
      run : echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
      
    - name : Lets test docker
      run : | 
        aws --version
        zip --version

