name: My-GithubActions

on:
  push:
    branches:
      - main
      
jobs:
  my_testing1:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello
      run : echo "Hello from testing"
      
  my_deploy2:
    runs-on: ubuntu-latest
    needs: [my_testing]
    steps:
    - name: Print Hello
      run : echo "Hello from deploy"

